AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'first-step-backend

  Sample SAM Template for first-step-backend

  '
Globals:
  Function:
    Timeout: 3
Resources:
  GetWorksListFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://dev-first-step-backend/6d69e0160589db38f32370deb385a207
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Role:
        Fn::GetAtt:
        - DynamoAccessRole
        - Arn
      Events:
        GetWorks:
          Type: Api
          Properties:
            Path: /get-works-list
            Method: get
  WorksTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: works-table
      PrimaryKey:
        Name: work_id
        Type: String
  DynamoAccessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Description: Role for accessing DynamoDB
      Path: /
      Policies:
      - PolicyName: dynamo-access-policy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - dynamodb:Scan
            Resource:
              Fn::GetAtt:
              - WorksTable
              - Arn
