AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  first-step-backend

  Sample SAM Template for first-step-backend

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  # Lambda関数
  GetWorksListFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: get-works-list/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Role: !GetAtt DynamoAccessRole.Arn
      Events:
        GetWorks:
          Type: Api
          Properties:
            Path: /get-works-list
            Method: get

  # DynamoDB
  WorksTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: works-table
      PrimaryKey:
        Name: work_id
        Type: String

  # IAM Role
  DynamoAccessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: "sts:AssumeRole"
      Description: "Role for accessing DynamoDB"
      Path: "/"
      Policies:
        - PolicyName: "dynamo-access-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - dynamodb:Scan
                Resource: !GetAtt WorksTable.Arn
